   version: 1
   services:
     - type: web
       name: your-bot-name
       env: python
       buildCommand: "pip install -r requirements.txt"
       startCommand: "python main.py"
       autoDeploy: true
   
